### ISSUE TITLE
Working with mouse data 

### ISSUE THREAD

**Issue by SziKayLeung** [TransBioInfoLab/MethReg#3]
Hi, 

Thanks for developing MethReg - we are keen to try it out! However, we are working with mouse methylation data (RRBS) rather than human data. Is it possible to use MethReg - though I've noticed that all of the genome parameters only allow "hg38" of "hg19" specification?

Thanks, 
Szi Kay

**Comment by tiagochst** [comment]
@SziKayLeung I added a new branch with some changes to use mouse data. But there is still work to be done. 
Just one notice, the package was mainly designed for array. We did not test it for RRBS or WGBS as far as I remember.

**Comment by SziKayLeung** [comment]
Hello @tiagochst, 

Thank you for working on this and informing us of the caveats! I'll have a go with the scripts in the new branch
